### ISSUE TITLE
Latest missing colors

### ISSUE THREAD

**Issue by the1glorfindel** [Xanthin/xaagle-colorfile#2]
Just used this again and got the following:
Unknown nodes:
beds:bed_bottom
beds:bed_top
beds:fancy_bed_bottom
beds:fancy_bed_top
bitchange:shop
default:ladder_wood
default:sign_wall_steel
default:sign_wall_wood
doors:door_steel_a
doors:gate_wood_closed
doors:hidden
ethereal:bush3
farming:barley_7
homedecor:armchair_white
homedecor:glass_table_large
inventory_plus:workbench
lapis:stone_with_lapis
lapis:stone_with_pyrite
mobs:stone
moreblocks:slab_steelblock
moreores:mineral_silver
moreores:mineral_tin
moreores:mithril_block
moreores:tin_block
smartshop:shop
stairs:corner_bronzeblock
stairs:corner_goldblock
stairs:corner_mithril_block
stairs:slab_aspen_wood
stairs:slab_steelblock
stairs:stair_aspen_wood
stairs:stair_bronzeblock
stairs:stair_goldblock
stairs:stair_mithril_block
walls:cobble
xanadu:poppy

I figured this would work better than me trying to add them ;)

**Comment by Xanthin** [comment]
Oh yes, I made my first map on Xanadu yesterday too and got such a reminder, that the list is pretty outdatet. Sorry, I hadn't much time the last weeks and thought, "tommorow, tommorow". Thank you for bringing this up. :) 

I will fix this today. But don't hesitate to come up with own solutions, it's just the average color value of a texture (and here or there some tweaks by hand for stuff with transparency, for example). :)

**Comment by Xanthin** [comment]
I updated the file. Everything noted in your missing-nodes-output should be fixed now.
Also, with a better structured list it should be easier now to check for and add in stuff. :)

**Comment by the1glorfindel** [comment]
Thanks a bunch!
Please don't feel hurried by me! I was just hoping to contribute a bit ;)
How do you get the average color value? Some gimp feature?

**Comment by Xanthin** [comment]
> How do you get the average color value? Some gimp feature?

~~If~~ When I do it manualy via gimp or paint.net, I just use the color picker tool.

**Comment by the1glorfindel** [comment]
Ahhh, I see... Thanks!

On Tue, Apr 19, 2016 at 7:37 AM -0700, "Xanthin" notifications@github.com wrote:

> How do you get the average color value? Some gimp feature?

If I do it manualy via gimp or paint.net, I just use the color picker tool.

---
